### PR TITLE
Always use the system default `DocumentBuilderFactory`, `TransformerFactory` and `XPathFactory`

### LINKED ISSUE #2454: Cannot render XML if another TransformerFactoryImpl exists
### Proposal

To support in-process integrations with applications that make use of libraries like Saxon

Since we're using JDK 17, Wm cannot use the internal JDK class, and because a different library brings in Saxon then Wm fails because Saxon does not support the indent attribute.

### Reproduction steps

wiremock v2.35.0
camel-spring-ws v3.20.2 which depends on 
Saxon-HE  v11.4 which doesn't support "indent-number" attribute

### References

Related issues:

#849 
#1072 
#1695

A possible solution from another project
https://github.com/nextgenhealthcare/connect/issues/1361#issuecomment-626880525
Implemented here
https://github.com/nextgenhealthcare/connect/commit/f1a31208bed28c8bd28225b3f0a442438362afd7

### PR DESCRIPTION
**Pull request by vkuzel**
Closes #2454
Related #2913

Followup to recently merged https://github.com/wiremock/wiremock/pull/2918 which solved the issue partly.

The `newInstance()` method of aforementioned classes may return a different implementation based on classes present on classpath. For example when `oracle.xml.jaxp.JXDocumentBuilderFactory` is present on the classpath, the use use of the `http://xml.org/sax/features/validation` attribute in the `Xml.java` file causes `ParserConfigurationException`.

The `newDefaultInstance()` method ensures consistency across different environment by using the same implementation irrespective to the classpath.

## References

- TODO

## Submitter checklist

- [ ] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [ ] Test coverage that demonstrates that the change works as expected
- [ ] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

### CODE REVIEW

File: src/main/java/com/github/tomakehurst/wiremock/common/xml/Xml.java [hunk 1]
```diff
@@ -116,7 +116,7 @@ private static TransformerFactory createTransformerFactory() {
                   .getDeclaredConstructor()
                   .newInstance();
```
Comment (jpraet) [inline src/main/java/com/github/tomakehurst/wiremock/common/xml/Xml.java:117]: On JDK17 this throws `java.lang.IllegalAccessException: class com.github.tomakehurst.wiremock.common.xml.Xml cannot access class com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xalan.internal.xsltc.trax to unnamed module @96532d6`.

Can't it be removed? Similar to how it's done here:

https://github.com/wiremock/wiremock/blob/fbf904da993830e6f16f4fb8d6d8e694d6645dae/src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/FormatXmlHelper.java#L68-L69
