### PR TITLE
[FIX] Add a custom number comparator to the Json Diff to trim trailing zeros

### LINKED ISSUE #2610: Decimals matching issue in wiremock 3.4.0
### Proposal

Wiremock 3.4.0 fails to match numbers with a floating point when the number has trailing zeros:

```
-----------------------------------------------------------------------------------------------------------------------
                                                           |
POST                                                       | POST
/test                                                      | /test
                                                           |
[equalToJson]                                              |                                                     <<<<< Body does not match
{                                                          | {
  "float" : 1.2                                            |   "float" : 1.2000
}                                                          | }
                                                           |
-----------------------------------------------------------------------------------------------------------------------
``` 

### Reproduction steps

1. Use JSON mapping below: 

```javascript
{
	"mappings": [
		{
			"request": {
				"method": "POST",
				"url": "/test",
				"bodyPatterns": [
					{
						"equalToJson": {
							"float": 1.2
						}
					}
				]
			},
			"response": {
				"status": 200
			}
		}
	]
}
``` 

2. Try making a request to `/test` with the request body as below - you will get expected 200 status code:
```javascript
{
  "float": 1.2
}
``` 
Or use the following curl:
```
curl -X POST -i --location "http://localhost:8080/test" \
    -H "Content-Type: application/json" \
    -d '{
          "float": 1.2000
        }'
```
3. Make the same request but with trailing zeros - expect the error
```javascript
{
  "float": 1.2000
}
``` 
curl:
```
curl -X POST -i --location "http://localhost:8080/test" \
    -H "Content-Type: application/json" \
    -d '{
          "float": 1.2000
        }'
```
4.  You'll get the error
```
HTTP/1.1 404 Not Found
Content-Type: text/plain;charset=UTF-8
Transfer-Encoding: chunked


                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
POST                                                       | POST
/test                                                      | /test
                                                           |
[equalToJson]                                              |                                                     <<<<< Body does not match
{                                                          | {
  "float" : 1.2                                            |   "float" : 1.2000
}                                                          | }
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

### References

The previous version of wiremock (3.3.1) works just fine for such a use case. Testing:
curl: 
```
curl -X POST -i --location "http://localhost:8080/test" \
    -H "Content-Type: application/json" \
    -d '{
          "float": 1.2000
        }'
```
Result:
```
HTTP/1.1 200 OK
Matched-Stub-Id: 4badb2ed-5773-4d9f-bcc2-4ba597f303c7
Transfer-Encoding: chunked
```

Perhaps the bug was introduced with #2588 : https://github.com/wiremock/wiremock/pull/2588/files#diff-ee455ccbdcabf0c0143b39e645b2e4e23198539b88bd90cf4eeeccf03ee21e1eR48

### PR DESCRIPTION
**Pull request by leeturner**
In PR [2588](https://github.com/wiremock/wiremock/pull/2588/files) we set our ObjectMapper to not normalise BigDecimal values.  This fixed the undesirable behavior of values such as this - `{"float": 2.0}` being changed to this - `{"float": 2}`.  This PR maintains that behaviour.   

Because decimal values are no longer being normalised, this means we have an issue with the json Diff not seeing numbers like `1.2` and `1.2000` as the same values. This change adds a new `NumberComparator` to the Diff to normalise the BigDecimal values so we can continue to compare those values in the same way as we used to in versions prior to `3.4.0`.

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

fixes #2610

### CODE REVIEW

File: src/test/java/com/github/tomakehurst/wiremock/testsupport/MappingJsonSamples.java [hunk 1]
```diff
@@ -257,4 +257,21 @@ public class MappingJsonSamples {
           + "           \"body\": \"国家标准\"                       \n"
           + "   }                                                                                          \n"
           + "}\n";
+
+  public static final String MAPPING_REQUEST_JSON_BODY_DECIMALS_NO_TRAILING_ZEROS =
```
Comment (leeturner) [inline src/test/java/com/github/tomakehurst/wiremock/testsupport/MappingJsonSamples.java:261]: These `\n` were all aligned in the editor :)

**Comment by tomakehurst** [comment]
Is there also a risk that this is broken for `matchesJsonPath`?

**Comment by leeturner** [comment]
> Is there also a risk that this is broken for `matchesJsonPath`?

I have added some tests to `MatchesJsonPathPatternTest` to validate we can match on decimals with and without trailing zeros.   Looks like it is find

**Review by tomakehurst — APPROVED** [review]
